#!/usr/bin/env bash
# Install what culebra builds with on Ubuntu, for a fresh dev machine.
#
#   ./misc/setup_ubuntu.sh
#
# Mirrors .github/actions/setup-linux-toolchain and install-just, which is
# the single source of truth this tracks — see those two files first if a
# package or version here looks stale. Only the base toolchain (no SDL3/
# Webview build deps, which the CI action gates behind flags for jobs that
# open a window); those two use apt package lists in
# .github/actions/setup-linux-toolchain/action.yml if you need them too.
#
# Tested against Ubuntu 24.04 (what CI runs on). Requires sudo.
set -eu

echo "==> Installing base packages"
# gcc-14: Ubuntu 24.04 ships gcc-13 by default, which lacks C++23 <print>.
# lsb-release/software-properties-common/gnupg are what apt.llvm.org's
# installer needs below.
sudo apt-get update
sudo apt-get install -y \
  ccache cmake g++-14 libblas-dev mold wget \
  lsb-release software-properties-common gnupg

echo "==> Installing just"
# The release asset, pinned to its published checksum, rather than
# just.systems/install.sh — matches install-just/action.yml. Ubuntu's
# apt-shipped just predates the [group(...)] attribute (just 1.27.0+).
just_ver=1.58.0
just_sha=4a5cc2f53e6f0f8c59092a6cc38291eb729d46a7dd95d3ae582008881b84931d
just_base=https://github.com/casey/just/releases/download
curl --proto '=https' --tlsv1.2 -sSfL --retry 3 --retry-delay 5 \
  -o /tmp/culebra-just.tar.gz \
  "$just_base/$just_ver/just-$just_ver-x86_64-unknown-linux-musl.tar.gz"
echo "$just_sha  /tmp/culebra-just.tar.gz" | sha256sum -c -
sudo tar -xzf /tmp/culebra-just.tar.gz -C /usr/local/bin just
rm /tmp/culebra-just.tar.gz
just --version

echo "==> Installing LLVM 22"
# Ubuntu 24.04's default llvm-dev (17/18) is too old — culebra's JIT uses
# LLVM 20+ APIs.
wget -qO /tmp/culebra-llvm.sh https://apt.llvm.org/llvm.sh
chmod +x /tmp/culebra-llvm.sh
sudo /tmp/culebra-llvm.sh 22
sudo apt-get install -y llvm-22-dev
rm /tmp/culebra-llvm.sh

env_file="$HOME/.culebra-env"
cat > "$env_file" <<'EOF'
# culebra build environment (generated by misc/setup_ubuntu.sh).
# CMAKE_PREFIX_PATH + LLVM_CONFIG matter together: without both, cmake
# silently configures with no JIT, and `--jit` is then read as a file name
# instead of being rejected.
export CC=gcc-14
export CXX=g++-14
export CMAKE_PREFIX_PATH=/usr/lib/llvm-22
export LLVM_CONFIG=/usr/lib/llvm-22/bin/llvm-config
EOF

cat <<EOF

==> Done. Wrote $env_file — source it in every shell that builds culebra:

    echo 'source "$env_file"' >> ~/.bashrc && source ~/.bashrc

Then, from the culebra checkout:

    just build      # -O3 + LTO, with JIT
    just test-dev     # quick gate (~80s)
EOF
