#!/usr/bin/env python3
# Read hex-encoded "patHex subjHex rlMatched rlStrHex" lines, adjudicate with
# Python's re (the oracle), keep only cases where regexlib already agrees, and
# emit a C++ data table. Deterministic order; capped count. Delete after.
import re, sys

def unhex(h): return bytes.fromhex(h)
def cppesc(b):  # every byte as \xNN (consecutive escapes are unambiguous)
    return ''.join('\\x%02x' % x for x in b)

kept, seen = [], set()
CAP = 400
for line in sys.stdin:
    parts = line.split()
    if len(parts) < 3: continue
    pat_h, subj_h, rl_m = parts[0], parts[1], parts[2]
    rl_s_h = parts[3] if len(parts) > 3 else ''
    pat, subj = unhex(pat_h), unhex(subj_h)
    rl_matched, rl_str = (rl_m == '1'), unhex(rl_s_h)
    key = (pat, subj)
    if key in seen: continue
    try:
        m = re.search(pat.decode('latin1'), subj.decode('latin1'))
    except re.error:
        continue
    py_matched = m is not None
    py_str = m.group(0).encode('latin1') if m else b''
    # keep only cases where regexlib already matches the Python oracle
    if py_matched == rl_matched and py_str == rl_str:
        seen.add(key)
        kept.append((pat, subj, py_matched, py_str))
        if len(kept) >= CAP: break

print('// Generated by gen_corpus.cpp + adjudicate.py — do not edit by hand.')
print('// Each case is Python-`re`-adjudicated; regexlib must reproduce it.')
print('// Cases where regexlib diverged from Python are excluded (see the')
print('// nullable-quantifier known limitation in regexlib_test.cc).')
print('#pragma once')
print('namespace regexlib_corpus {')
print('struct Case { const char* pattern; const char* subject; bool matched; const char* expected; };')
print('static const Case kCases[] = {')
for pat, subj, m, s in kept:
    print('  {"%s", "%s", %s, "%s"},' % (cppesc(pat), cppesc(subj),
                                         'true' if m else 'false', cppesc(s)))
print('};')
print('static const int kCaseCount = %d;' % len(kept))
print('}  // namespace regexlib_corpus')
sys.stderr.write('kept %d cases\n' % len(kept))
