/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 16
#define LARGE_STATE_COUNT 15
#define SYMBOL_COUNT 64
#define ALIAS_COUNT 0
#define TOKEN_COUNT 51
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 2
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_line_comment = 2,
  sym_block_comment = 3,
  sym_kw_function = 4,
  anon_sym_class = 5,
  anon_sym_trait = 6,
  anon_sym_enum = 7,
  anon_sym_if = 8,
  anon_sym_else = 9,
  anon_sym_match = 10,
  anon_sym_cond = 11,
  anon_sym_while = 12,
  anon_sym_for = 13,
  anon_sym_in = 14,
  anon_sym_return = 15,
  anon_sym_break = 16,
  anon_sym_continue = 17,
  anon_sym_throw = 18,
  anon_sym_try = 19,
  anon_sym_catch = 20,
  anon_sym_defer = 21,
  anon_sym_yield = 22,
  anon_sym_import = 23,
  anon_sym_export = 24,
  anon_sym_from = 25,
  sym_kw_debugger = 26,
  anon_sym_let = 27,
  anon_sym_mut = 28,
  anon_sym_static = 29,
  anon_sym_true = 30,
  anon_sym_false = 31,
  sym_nil = 32,
  anon_sym_self = 33,
  anon_sym_this = 34,
  anon_sym___ARGS__ = 35,
  sym_number = 36,
  sym_string = 37,
  sym_regex = 38,
  sym_type = 39,
  anon_sym_LPAREN = 40,
  sym_operator = 41,
  anon_sym_LPAREN2 = 42,
  anon_sym_RPAREN = 43,
  anon_sym_LBRACK = 44,
  anon_sym_RBRACK = 45,
  anon_sym_LBRACE = 46,
  anon_sym_RBRACE = 47,
  anon_sym_COMMA = 48,
  anon_sym_DOT = 49,
  anon_sym_SEMI = 50,
  sym_source_file = 51,
  sym__token = 52,
  sym_kw_class = 53,
  sym_kw_conditional = 54,
  sym_kw_repeat = 55,
  sym_kw_statement = 56,
  sym_kw_include = 57,
  sym_storage = 58,
  sym_boolean = 59,
  sym_self = 60,
  sym_call = 61,
  sym_punctuation = 62,
  aux_sym_source_file_repeat1 = 63,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_line_comment] = "line_comment",
  [sym_block_comment] = "block_comment",
  [sym_kw_function] = "kw_function",
  [anon_sym_class] = "class",
  [anon_sym_trait] = "trait",
  [anon_sym_enum] = "enum",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [anon_sym_match] = "match",
  [anon_sym_cond] = "cond",
  [anon_sym_while] = "while",
  [anon_sym_for] = "for",
  [anon_sym_in] = "in",
  [anon_sym_return] = "return",
  [anon_sym_break] = "break",
  [anon_sym_continue] = "continue",
  [anon_sym_throw] = "throw",
  [anon_sym_try] = "try",
  [anon_sym_catch] = "catch",
  [anon_sym_defer] = "defer",
  [anon_sym_yield] = "yield",
  [anon_sym_import] = "import",
  [anon_sym_export] = "export",
  [anon_sym_from] = "from",
  [sym_kw_debugger] = "kw_debugger",
  [anon_sym_let] = "let",
  [anon_sym_mut] = "mut",
  [anon_sym_static] = "static",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_nil] = "nil",
  [anon_sym_self] = "self",
  [anon_sym_this] = "this",
  [anon_sym___ARGS__] = "__ARGS__",
  [sym_number] = "number",
  [sym_string] = "string",
  [sym_regex] = "regex",
  [sym_type] = "type",
  [anon_sym_LPAREN] = "(",
  [sym_operator] = "operator",
  [anon_sym_LPAREN2] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COMMA] = ",",
  [anon_sym_DOT] = ".",
  [anon_sym_SEMI] = ";",
  [sym_source_file] = "source_file",
  [sym__token] = "_token",
  [sym_kw_class] = "kw_class",
  [sym_kw_conditional] = "kw_conditional",
  [sym_kw_repeat] = "kw_repeat",
  [sym_kw_statement] = "kw_statement",
  [sym_kw_include] = "kw_include",
  [sym_storage] = "storage",
  [sym_boolean] = "boolean",
  [sym_self] = "self",
  [sym_call] = "call",
  [sym_punctuation] = "punctuation",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_line_comment] = sym_line_comment,
  [sym_block_comment] = sym_block_comment,
  [sym_kw_function] = sym_kw_function,
  [anon_sym_class] = anon_sym_class,
  [anon_sym_trait] = anon_sym_trait,
  [anon_sym_enum] = anon_sym_enum,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_match] = anon_sym_match,
  [anon_sym_cond] = anon_sym_cond,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_for] = anon_sym_for,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_break] = anon_sym_break,
  [anon_sym_continue] = anon_sym_continue,
  [anon_sym_throw] = anon_sym_throw,
  [anon_sym_try] = anon_sym_try,
  [anon_sym_catch] = anon_sym_catch,
  [anon_sym_defer] = anon_sym_defer,
  [anon_sym_yield] = anon_sym_yield,
  [anon_sym_import] = anon_sym_import,
  [anon_sym_export] = anon_sym_export,
  [anon_sym_from] = anon_sym_from,
  [sym_kw_debugger] = sym_kw_debugger,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_mut] = anon_sym_mut,
  [anon_sym_static] = anon_sym_static,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_nil] = sym_nil,
  [anon_sym_self] = anon_sym_self,
  [anon_sym_this] = anon_sym_this,
  [anon_sym___ARGS__] = anon_sym___ARGS__,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [sym_regex] = sym_regex,
  [sym_type] = sym_type,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [sym_operator] = sym_operator,
  [anon_sym_LPAREN2] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_source_file] = sym_source_file,
  [sym__token] = sym__token,
  [sym_kw_class] = sym_kw_class,
  [sym_kw_conditional] = sym_kw_conditional,
  [sym_kw_repeat] = sym_kw_repeat,
  [sym_kw_statement] = sym_kw_statement,
  [sym_kw_include] = sym_kw_include,
  [sym_storage] = sym_storage,
  [sym_boolean] = sym_boolean,
  [sym_self] = sym_self,
  [sym_call] = sym_call,
  [sym_punctuation] = sym_punctuation,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_function] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_class] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_trait] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_enum] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_match] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_cond] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_break] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_continue] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_throw] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_try] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_catch] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_defer] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_yield] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_export] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_from] = {
    .visible = true,
    .named = false,
  },
  [sym_kw_debugger] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_mut] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_static] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_nil] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_self] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_this] = {
    .visible = true,
    .named = false,
  },
  [anon_sym___ARGS__] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_regex] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__token] = {
    .visible = false,
    .named = true,
  },
  [sym_kw_class] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_conditional] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_repeat] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_include] = {
    .visible = true,
    .named = true,
  },
  [sym_storage] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_self] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_punctuation] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_name = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(17);
      ADVANCE_MAP(
        '!', 32,
        '"', 1,
        '#', 18,
        '%', 32,
        '&', 34,
        '\'', 3,
        '(', 29,
        ')', 40,
        '*', 35,
        '+', 32,
        ',', 45,
        '-', 38,
        '.', 46,
        '/', 31,
        ':', 30,
        ';', 47,
        '<', 32,
        '=', 38,
        '>', 32,
        '?', 33,
        '@', 32,
        '[', 41,
        ']', 42,
        '^', 32,
        'r', 26,
        '{', 43,
        '|', 37,
        '}', 44,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(28);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(23);
      if (lookahead == '\\') ADVANCE(11);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(24);
      if (lookahead == '\\') ADVANCE(14);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(23);
      if (lookahead == '\\') ADVANCE(12);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '\'') ADVANCE(24);
      if (lookahead == '\\') ADVANCE(15);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(19);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '\\') ADVANCE(13);
      if (lookahead == '`') ADVANCE(24);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      END_STATE();
    case 9:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      END_STATE();
    case 11:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 12:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 13:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(7);
      END_STATE();
    case 14:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 15:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(4);
      END_STATE();
    case 16:
      if (eof) ADVANCE(17);
      ADVANCE_MAP(
        '!', 32,
        '"', 1,
        '#', 18,
        '%', 32,
        '&', 34,
        '\'', 3,
        '(', 39,
        ')', 40,
        '*', 35,
        '+', 32,
        ',', 45,
        '-', 38,
        '.', 46,
        '/', 31,
        ':', 30,
        ';', 47,
        '<', 32,
        '=', 38,
        '>', 32,
        '?', 33,
        '@', 32,
        '[', 41,
        ']', 42,
        '^', 32,
        'r', 26,
        '{', 43,
        '|', 37,
        '}', 44,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(28);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_block_comment);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(9);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_regex);
      if (lookahead == 'i' ||
          lookahead == 'm' ||
          lookahead == 's') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '\'') ADVANCE(4);
      if (lookahead == '`') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_type);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_operator);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '/') ADVANCE(18);
      if (lookahead == '=') ADVANCE(30);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '=') ADVANCE(30);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '?') ADVANCE(30);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '&' ||
          lookahead == '=') ADVANCE(30);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '*' ||
          lookahead == '=') ADVANCE(30);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '.' ||
          lookahead == '=') ADVANCE(30);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '=' ||
          lookahead == '|') ADVANCE(30);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '=' ||
          lookahead == '>') ADVANCE(30);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LPAREN2);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (lookahead == '.') ADVANCE(36);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        '_', 1,
        'b', 2,
        'c', 3,
        'd', 4,
        'e', 5,
        'f', 6,
        'i', 7,
        'l', 8,
        'm', 9,
        'n', 10,
        'r', 11,
        's', 12,
        't', 13,
        'w', 14,
        'y', 15,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '_') ADVANCE(16);
      END_STATE();
    case 2:
      if (lookahead == 'r') ADVANCE(17);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(18);
      if (lookahead == 'l') ADVANCE(19);
      if (lookahead == 'o') ADVANCE(20);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 5:
      if (lookahead == 'l') ADVANCE(22);
      if (lookahead == 'n') ADVANCE(23);
      if (lookahead == 'x') ADVANCE(24);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(25);
      if (lookahead == 'n') ADVANCE(26);
      if (lookahead == 'o') ADVANCE(27);
      if (lookahead == 'r') ADVANCE(28);
      END_STATE();
    case 7:
      if (lookahead == 'f') ADVANCE(29);
      if (lookahead == 'm') ADVANCE(30);
      if (lookahead == 'n') ADVANCE(31);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(32);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(33);
      if (lookahead == 'u') ADVANCE(34);
      END_STATE();
    case 10:
      if (lookahead == 'i') ADVANCE(35);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(36);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(37);
      if (lookahead == 't') ADVANCE(38);
      END_STATE();
    case 13:
      if (lookahead == 'h') ADVANCE(39);
      if (lookahead == 'r') ADVANCE(40);
      END_STATE();
    case 14:
      if (lookahead == 'h') ADVANCE(41);
      END_STATE();
    case 15:
      if (lookahead == 'i') ADVANCE(42);
      END_STATE();
    case 16:
      if (lookahead == 'A') ADVANCE(43);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(44);
      END_STATE();
    case 18:
      if (lookahead == 't') ADVANCE(45);
      END_STATE();
    case 19:
      if (lookahead == 'a') ADVANCE(46);
      END_STATE();
    case 20:
      if (lookahead == 'n') ADVANCE(47);
      END_STATE();
    case 21:
      if (lookahead == 'b') ADVANCE(48);
      if (lookahead == 'f') ADVANCE(49);
      END_STATE();
    case 22:
      if (lookahead == 's') ADVANCE(50);
      END_STATE();
    case 23:
      if (lookahead == 'u') ADVANCE(51);
      END_STATE();
    case 24:
      if (lookahead == 'p') ADVANCE(52);
      END_STATE();
    case 25:
      if (lookahead == 'l') ADVANCE(53);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_kw_function);
      END_STATE();
    case 27:
      if (lookahead == 'r') ADVANCE(54);
      END_STATE();
    case 28:
      if (lookahead == 'o') ADVANCE(55);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 30:
      if (lookahead == 'p') ADVANCE(56);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 32:
      if (lookahead == 't') ADVANCE(57);
      END_STATE();
    case 33:
      if (lookahead == 't') ADVANCE(58);
      END_STATE();
    case 34:
      if (lookahead == 't') ADVANCE(59);
      END_STATE();
    case 35:
      if (lookahead == 'l') ADVANCE(60);
      END_STATE();
    case 36:
      if (lookahead == 't') ADVANCE(61);
      END_STATE();
    case 37:
      if (lookahead == 'l') ADVANCE(62);
      END_STATE();
    case 38:
      if (lookahead == 'a') ADVANCE(63);
      END_STATE();
    case 39:
      if (lookahead == 'i') ADVANCE(64);
      if (lookahead == 'r') ADVANCE(65);
      END_STATE();
    case 40:
      if (lookahead == 'a') ADVANCE(66);
      if (lookahead == 'u') ADVANCE(67);
      if (lookahead == 'y') ADVANCE(68);
      END_STATE();
    case 41:
      if (lookahead == 'i') ADVANCE(69);
      END_STATE();
    case 42:
      if (lookahead == 'e') ADVANCE(70);
      END_STATE();
    case 43:
      if (lookahead == 'R') ADVANCE(71);
      END_STATE();
    case 44:
      if (lookahead == 'a') ADVANCE(72);
      END_STATE();
    case 45:
      if (lookahead == 'c') ADVANCE(73);
      END_STATE();
    case 46:
      if (lookahead == 's') ADVANCE(74);
      END_STATE();
    case 47:
      if (lookahead == 'd') ADVANCE(75);
      if (lookahead == 't') ADVANCE(76);
      END_STATE();
    case 48:
      if (lookahead == 'u') ADVANCE(77);
      END_STATE();
    case 49:
      if (lookahead == 'e') ADVANCE(78);
      END_STATE();
    case 50:
      if (lookahead == 'e') ADVANCE(79);
      END_STATE();
    case 51:
      if (lookahead == 'm') ADVANCE(80);
      END_STATE();
    case 52:
      if (lookahead == 'o') ADVANCE(81);
      END_STATE();
    case 53:
      if (lookahead == 's') ADVANCE(82);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_for);
      END_STATE();
    case 55:
      if (lookahead == 'm') ADVANCE(83);
      END_STATE();
    case 56:
      if (lookahead == 'o') ADVANCE(84);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 58:
      if (lookahead == 'c') ADVANCE(85);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_mut);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_nil);
      END_STATE();
    case 61:
      if (lookahead == 'u') ADVANCE(86);
      END_STATE();
    case 62:
      if (lookahead == 'f') ADVANCE(87);
      END_STATE();
    case 63:
      if (lookahead == 't') ADVANCE(88);
      END_STATE();
    case 64:
      if (lookahead == 's') ADVANCE(89);
      END_STATE();
    case 65:
      if (lookahead == 'o') ADVANCE(90);
      END_STATE();
    case 66:
      if (lookahead == 'i') ADVANCE(91);
      END_STATE();
    case 67:
      if (lookahead == 'e') ADVANCE(92);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_try);
      END_STATE();
    case 69:
      if (lookahead == 'l') ADVANCE(93);
      END_STATE();
    case 70:
      if (lookahead == 'l') ADVANCE(94);
      END_STATE();
    case 71:
      if (lookahead == 'G') ADVANCE(95);
      END_STATE();
    case 72:
      if (lookahead == 'k') ADVANCE(96);
      END_STATE();
    case 73:
      if (lookahead == 'h') ADVANCE(97);
      END_STATE();
    case 74:
      if (lookahead == 's') ADVANCE(98);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_cond);
      END_STATE();
    case 76:
      if (lookahead == 'i') ADVANCE(99);
      END_STATE();
    case 77:
      if (lookahead == 'g') ADVANCE(100);
      END_STATE();
    case 78:
      if (lookahead == 'r') ADVANCE(101);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_enum);
      END_STATE();
    case 81:
      if (lookahead == 'r') ADVANCE(102);
      END_STATE();
    case 82:
      if (lookahead == 'e') ADVANCE(103);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_from);
      END_STATE();
    case 84:
      if (lookahead == 'r') ADVANCE(104);
      END_STATE();
    case 85:
      if (lookahead == 'h') ADVANCE(105);
      END_STATE();
    case 86:
      if (lookahead == 'r') ADVANCE(106);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_self);
      END_STATE();
    case 88:
      if (lookahead == 'i') ADVANCE(107);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_this);
      END_STATE();
    case 90:
      if (lookahead == 'w') ADVANCE(108);
      END_STATE();
    case 91:
      if (lookahead == 't') ADVANCE(109);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 93:
      if (lookahead == 'e') ADVANCE(110);
      END_STATE();
    case 94:
      if (lookahead == 'd') ADVANCE(111);
      END_STATE();
    case 95:
      if (lookahead == 'S') ADVANCE(112);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_break);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_catch);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_class);
      END_STATE();
    case 99:
      if (lookahead == 'n') ADVANCE(113);
      END_STATE();
    case 100:
      if (lookahead == 'g') ADVANCE(114);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_defer);
      END_STATE();
    case 102:
      if (lookahead == 't') ADVANCE(115);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 104:
      if (lookahead == 't') ADVANCE(116);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_match);
      END_STATE();
    case 106:
      if (lookahead == 'n') ADVANCE(117);
      END_STATE();
    case 107:
      if (lookahead == 'c') ADVANCE(118);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_throw);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_trait);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_while);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_yield);
      END_STATE();
    case 112:
      if (lookahead == '_') ADVANCE(119);
      END_STATE();
    case 113:
      if (lookahead == 'u') ADVANCE(120);
      END_STATE();
    case 114:
      if (lookahead == 'e') ADVANCE(121);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(anon_sym_export);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_import);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(anon_sym_static);
      END_STATE();
    case 119:
      if (lookahead == '_') ADVANCE(122);
      END_STATE();
    case 120:
      if (lookahead == 'e') ADVANCE(123);
      END_STATE();
    case 121:
      if (lookahead == 'r') ADVANCE(124);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(anon_sym___ARGS__);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(anon_sym_continue);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_kw_debugger);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 16},
  [2] = {.lex_state = 16},
  [3] = {.lex_state = 16},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 16},
  [6] = {.lex_state = 16},
  [7] = {.lex_state = 16},
  [8] = {.lex_state = 16},
  [9] = {.lex_state = 16},
  [10] = {.lex_state = 16},
  [11] = {.lex_state = 16},
  [12] = {.lex_state = 16},
  [13] = {.lex_state = 16},
  [14] = {.lex_state = 16},
  [15] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_kw_function] = ACTIONS(1),
    [anon_sym_class] = ACTIONS(1),
    [anon_sym_trait] = ACTIONS(1),
    [anon_sym_enum] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_match] = ACTIONS(1),
    [anon_sym_cond] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_break] = ACTIONS(1),
    [anon_sym_continue] = ACTIONS(1),
    [anon_sym_throw] = ACTIONS(1),
    [anon_sym_try] = ACTIONS(1),
    [anon_sym_catch] = ACTIONS(1),
    [anon_sym_defer] = ACTIONS(1),
    [anon_sym_yield] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_export] = ACTIONS(1),
    [anon_sym_from] = ACTIONS(1),
    [sym_kw_debugger] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_mut] = ACTIONS(1),
    [anon_sym_static] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_nil] = ACTIONS(1),
    [anon_sym_self] = ACTIONS(1),
    [anon_sym_this] = ACTIONS(1),
    [anon_sym___ARGS__] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_regex] = ACTIONS(1),
    [sym_type] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [sym_operator] = ACTIONS(1),
    [anon_sym_LPAREN2] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(15),
    [sym__token] = STATE(2),
    [sym_kw_class] = STATE(2),
    [sym_kw_conditional] = STATE(2),
    [sym_kw_repeat] = STATE(2),
    [sym_kw_statement] = STATE(2),
    [sym_kw_include] = STATE(2),
    [sym_storage] = STATE(2),
    [sym_boolean] = STATE(2),
    [sym_self] = STATE(2),
    [sym_call] = STATE(2),
    [sym_punctuation] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_kw_function] = ACTIONS(9),
    [anon_sym_class] = ACTIONS(11),
    [anon_sym_trait] = ACTIONS(11),
    [anon_sym_enum] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_else] = ACTIONS(13),
    [anon_sym_match] = ACTIONS(13),
    [anon_sym_cond] = ACTIONS(13),
    [anon_sym_while] = ACTIONS(15),
    [anon_sym_for] = ACTIONS(15),
    [anon_sym_in] = ACTIONS(15),
    [anon_sym_return] = ACTIONS(17),
    [anon_sym_break] = ACTIONS(17),
    [anon_sym_continue] = ACTIONS(17),
    [anon_sym_throw] = ACTIONS(17),
    [anon_sym_try] = ACTIONS(17),
    [anon_sym_catch] = ACTIONS(17),
    [anon_sym_defer] = ACTIONS(17),
    [anon_sym_yield] = ACTIONS(17),
    [anon_sym_import] = ACTIONS(19),
    [anon_sym_export] = ACTIONS(19),
    [anon_sym_from] = ACTIONS(19),
    [sym_kw_debugger] = ACTIONS(9),
    [anon_sym_let] = ACTIONS(21),
    [anon_sym_mut] = ACTIONS(21),
    [anon_sym_static] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [sym_nil] = ACTIONS(9),
    [anon_sym_self] = ACTIONS(25),
    [anon_sym_this] = ACTIONS(25),
    [anon_sym___ARGS__] = ACTIONS(25),
    [sym_number] = ACTIONS(27),
    [sym_string] = ACTIONS(27),
    [sym_regex] = ACTIONS(27),
    [sym_type] = ACTIONS(29),
    [sym_operator] = ACTIONS(9),
    [anon_sym_LPAREN2] = ACTIONS(31),
    [anon_sym_RPAREN] = ACTIONS(31),
    [anon_sym_LBRACK] = ACTIONS(31),
    [anon_sym_RBRACK] = ACTIONS(31),
    [anon_sym_LBRACE] = ACTIONS(31),
    [anon_sym_RBRACE] = ACTIONS(31),
    [anon_sym_COMMA] = ACTIONS(31),
    [anon_sym_DOT] = ACTIONS(33),
    [anon_sym_SEMI] = ACTIONS(31),
  },
  [STATE(2)] = {
    [sym__token] = STATE(3),
    [sym_kw_class] = STATE(3),
    [sym_kw_conditional] = STATE(3),
    [sym_kw_repeat] = STATE(3),
    [sym_kw_statement] = STATE(3),
    [sym_kw_include] = STATE(3),
    [sym_storage] = STATE(3),
    [sym_boolean] = STATE(3),
    [sym_self] = STATE(3),
    [sym_call] = STATE(3),
    [sym_punctuation] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(35),
    [sym_identifier] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_kw_function] = ACTIONS(37),
    [anon_sym_class] = ACTIONS(11),
    [anon_sym_trait] = ACTIONS(11),
    [anon_sym_enum] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_else] = ACTIONS(13),
    [anon_sym_match] = ACTIONS(13),
    [anon_sym_cond] = ACTIONS(13),
    [anon_sym_while] = ACTIONS(15),
    [anon_sym_for] = ACTIONS(15),
    [anon_sym_in] = ACTIONS(15),
    [anon_sym_return] = ACTIONS(17),
    [anon_sym_break] = ACTIONS(17),
    [anon_sym_continue] = ACTIONS(17),
    [anon_sym_throw] = ACTIONS(17),
    [anon_sym_try] = ACTIONS(17),
    [anon_sym_catch] = ACTIONS(17),
    [anon_sym_defer] = ACTIONS(17),
    [anon_sym_yield] = ACTIONS(17),
    [anon_sym_import] = ACTIONS(19),
    [anon_sym_export] = ACTIONS(19),
    [anon_sym_from] = ACTIONS(19),
    [sym_kw_debugger] = ACTIONS(37),
    [anon_sym_let] = ACTIONS(21),
    [anon_sym_mut] = ACTIONS(21),
    [anon_sym_static] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [sym_nil] = ACTIONS(37),
    [anon_sym_self] = ACTIONS(25),
    [anon_sym_this] = ACTIONS(25),
    [anon_sym___ARGS__] = ACTIONS(25),
    [sym_number] = ACTIONS(39),
    [sym_string] = ACTIONS(39),
    [sym_regex] = ACTIONS(39),
    [sym_type] = ACTIONS(29),
    [sym_operator] = ACTIONS(37),
    [anon_sym_LPAREN2] = ACTIONS(31),
    [anon_sym_RPAREN] = ACTIONS(31),
    [anon_sym_LBRACK] = ACTIONS(31),
    [anon_sym_RBRACK] = ACTIONS(31),
    [anon_sym_LBRACE] = ACTIONS(31),
    [anon_sym_RBRACE] = ACTIONS(31),
    [anon_sym_COMMA] = ACTIONS(31),
    [anon_sym_DOT] = ACTIONS(33),
    [anon_sym_SEMI] = ACTIONS(31),
  },
  [STATE(3)] = {
    [sym__token] = STATE(3),
    [sym_kw_class] = STATE(3),
    [sym_kw_conditional] = STATE(3),
    [sym_kw_repeat] = STATE(3),
    [sym_kw_statement] = STATE(3),
    [sym_kw_include] = STATE(3),
    [sym_storage] = STATE(3),
    [sym_boolean] = STATE(3),
    [sym_self] = STATE(3),
    [sym_call] = STATE(3),
    [sym_punctuation] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(41),
    [sym_identifier] = ACTIONS(43),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_kw_function] = ACTIONS(46),
    [anon_sym_class] = ACTIONS(49),
    [anon_sym_trait] = ACTIONS(49),
    [anon_sym_enum] = ACTIONS(49),
    [anon_sym_if] = ACTIONS(52),
    [anon_sym_else] = ACTIONS(52),
    [anon_sym_match] = ACTIONS(52),
    [anon_sym_cond] = ACTIONS(52),
    [anon_sym_while] = ACTIONS(55),
    [anon_sym_for] = ACTIONS(55),
    [anon_sym_in] = ACTIONS(55),
    [anon_sym_return] = ACTIONS(58),
    [anon_sym_break] = ACTIONS(58),
    [anon_sym_continue] = ACTIONS(58),
    [anon_sym_throw] = ACTIONS(58),
    [anon_sym_try] = ACTIONS(58),
    [anon_sym_catch] = ACTIONS(58),
    [anon_sym_defer] = ACTIONS(58),
    [anon_sym_yield] = ACTIONS(58),
    [anon_sym_import] = ACTIONS(61),
    [anon_sym_export] = ACTIONS(61),
    [anon_sym_from] = ACTIONS(61),
    [sym_kw_debugger] = ACTIONS(46),
    [anon_sym_let] = ACTIONS(64),
    [anon_sym_mut] = ACTIONS(64),
    [anon_sym_static] = ACTIONS(64),
    [anon_sym_true] = ACTIONS(67),
    [anon_sym_false] = ACTIONS(67),
    [sym_nil] = ACTIONS(46),
    [anon_sym_self] = ACTIONS(70),
    [anon_sym_this] = ACTIONS(70),
    [anon_sym___ARGS__] = ACTIONS(70),
    [sym_number] = ACTIONS(73),
    [sym_string] = ACTIONS(73),
    [sym_regex] = ACTIONS(73),
    [sym_type] = ACTIONS(76),
    [sym_operator] = ACTIONS(46),
    [anon_sym_LPAREN2] = ACTIONS(79),
    [anon_sym_RPAREN] = ACTIONS(79),
    [anon_sym_LBRACK] = ACTIONS(79),
    [anon_sym_RBRACK] = ACTIONS(79),
    [anon_sym_LBRACE] = ACTIONS(79),
    [anon_sym_RBRACE] = ACTIONS(79),
    [anon_sym_COMMA] = ACTIONS(79),
    [anon_sym_DOT] = ACTIONS(82),
    [anon_sym_SEMI] = ACTIONS(79),
  },
  [STATE(4)] = {
    [ts_builtin_sym_end] = ACTIONS(85),
    [sym_identifier] = ACTIONS(87),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_kw_function] = ACTIONS(87),
    [anon_sym_class] = ACTIONS(87),
    [anon_sym_trait] = ACTIONS(87),
    [anon_sym_enum] = ACTIONS(87),
    [anon_sym_if] = ACTIONS(87),
    [anon_sym_else] = ACTIONS(87),
    [anon_sym_match] = ACTIONS(87),
    [anon_sym_cond] = ACTIONS(87),
    [anon_sym_while] = ACTIONS(87),
    [anon_sym_for] = ACTIONS(87),
    [anon_sym_in] = ACTIONS(87),
    [anon_sym_return] = ACTIONS(87),
    [anon_sym_break] = ACTIONS(87),
    [anon_sym_continue] = ACTIONS(87),
    [anon_sym_throw] = ACTIONS(87),
    [anon_sym_try] = ACTIONS(87),
    [anon_sym_catch] = ACTIONS(87),
    [anon_sym_defer] = ACTIONS(87),
    [anon_sym_yield] = ACTIONS(87),
    [anon_sym_import] = ACTIONS(87),
    [anon_sym_export] = ACTIONS(87),
    [anon_sym_from] = ACTIONS(87),
    [sym_kw_debugger] = ACTIONS(87),
    [anon_sym_let] = ACTIONS(87),
    [anon_sym_mut] = ACTIONS(87),
    [anon_sym_static] = ACTIONS(87),
    [anon_sym_true] = ACTIONS(87),
    [anon_sym_false] = ACTIONS(87),
    [sym_nil] = ACTIONS(87),
    [anon_sym_self] = ACTIONS(87),
    [anon_sym_this] = ACTIONS(87),
    [anon_sym___ARGS__] = ACTIONS(87),
    [sym_number] = ACTIONS(85),
    [sym_string] = ACTIONS(85),
    [sym_regex] = ACTIONS(85),
    [sym_type] = ACTIONS(85),
    [anon_sym_LPAREN] = ACTIONS(89),
    [sym_operator] = ACTIONS(87),
    [anon_sym_LPAREN2] = ACTIONS(87),
    [anon_sym_RPAREN] = ACTIONS(85),
    [anon_sym_LBRACK] = ACTIONS(85),
    [anon_sym_RBRACK] = ACTIONS(85),
    [anon_sym_LBRACE] = ACTIONS(85),
    [anon_sym_RBRACE] = ACTIONS(85),
    [anon_sym_COMMA] = ACTIONS(85),
    [anon_sym_DOT] = ACTIONS(87),
    [anon_sym_SEMI] = ACTIONS(85),
  },
  [STATE(5)] = {
    [ts_builtin_sym_end] = ACTIONS(91),
    [sym_identifier] = ACTIONS(93),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_kw_function] = ACTIONS(93),
    [anon_sym_class] = ACTIONS(93),
    [anon_sym_trait] = ACTIONS(93),
    [anon_sym_enum] = ACTIONS(93),
    [anon_sym_if] = ACTIONS(93),
    [anon_sym_else] = ACTIONS(93),
    [anon_sym_match] = ACTIONS(93),
    [anon_sym_cond] = ACTIONS(93),
    [anon_sym_while] = ACTIONS(93),
    [anon_sym_for] = ACTIONS(93),
    [anon_sym_in] = ACTIONS(93),
    [anon_sym_return] = ACTIONS(93),
    [anon_sym_break] = ACTIONS(93),
    [anon_sym_continue] = ACTIONS(93),
    [anon_sym_throw] = ACTIONS(93),
    [anon_sym_try] = ACTIONS(93),
    [anon_sym_catch] = ACTIONS(93),
    [anon_sym_defer] = ACTIONS(93),
    [anon_sym_yield] = ACTIONS(93),
    [anon_sym_import] = ACTIONS(93),
    [anon_sym_export] = ACTIONS(93),
    [anon_sym_from] = ACTIONS(93),
    [sym_kw_debugger] = ACTIONS(93),
    [anon_sym_let] = ACTIONS(93),
    [anon_sym_mut] = ACTIONS(93),
    [anon_sym_static] = ACTIONS(93),
    [anon_sym_true] = ACTIONS(93),
    [anon_sym_false] = ACTIONS(93),
    [sym_nil] = ACTIONS(93),
    [anon_sym_self] = ACTIONS(93),
    [anon_sym_this] = ACTIONS(93),
    [anon_sym___ARGS__] = ACTIONS(93),
    [sym_number] = ACTIONS(91),
    [sym_string] = ACTIONS(91),
    [sym_regex] = ACTIONS(91),
    [sym_type] = ACTIONS(91),
    [sym_operator] = ACTIONS(93),
    [anon_sym_LPAREN2] = ACTIONS(91),
    [anon_sym_RPAREN] = ACTIONS(91),
    [anon_sym_LBRACK] = ACTIONS(91),
    [anon_sym_RBRACK] = ACTIONS(91),
    [anon_sym_LBRACE] = ACTIONS(91),
    [anon_sym_RBRACE] = ACTIONS(91),
    [anon_sym_COMMA] = ACTIONS(91),
    [anon_sym_DOT] = ACTIONS(93),
    [anon_sym_SEMI] = ACTIONS(91),
  },
  [STATE(6)] = {
    [ts_builtin_sym_end] = ACTIONS(95),
    [sym_identifier] = ACTIONS(97),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_kw_function] = ACTIONS(97),
    [anon_sym_class] = ACTIONS(97),
    [anon_sym_trait] = ACTIONS(97),
    [anon_sym_enum] = ACTIONS(97),
    [anon_sym_if] = ACTIONS(97),
    [anon_sym_else] = ACTIONS(97),
    [anon_sym_match] = ACTIONS(97),
    [anon_sym_cond] = ACTIONS(97),
    [anon_sym_while] = ACTIONS(97),
    [anon_sym_for] = ACTIONS(97),
    [anon_sym_in] = ACTIONS(97),
    [anon_sym_return] = ACTIONS(97),
    [anon_sym_break] = ACTIONS(97),
    [anon_sym_continue] = ACTIONS(97),
    [anon_sym_throw] = ACTIONS(97),
    [anon_sym_try] = ACTIONS(97),
    [anon_sym_catch] = ACTIONS(97),
    [anon_sym_defer] = ACTIONS(97),
    [anon_sym_yield] = ACTIONS(97),
    [anon_sym_import] = ACTIONS(97),
    [anon_sym_export] = ACTIONS(97),
    [anon_sym_from] = ACTIONS(97),
    [sym_kw_debugger] = ACTIONS(97),
    [anon_sym_let] = ACTIONS(97),
    [anon_sym_mut] = ACTIONS(97),
    [anon_sym_static] = ACTIONS(97),
    [anon_sym_true] = ACTIONS(97),
    [anon_sym_false] = ACTIONS(97),
    [sym_nil] = ACTIONS(97),
    [anon_sym_self] = ACTIONS(97),
    [anon_sym_this] = ACTIONS(97),
    [anon_sym___ARGS__] = ACTIONS(97),
    [sym_number] = ACTIONS(95),
    [sym_string] = ACTIONS(95),
    [sym_regex] = ACTIONS(95),
    [sym_type] = ACTIONS(95),
    [sym_operator] = ACTIONS(97),
    [anon_sym_LPAREN2] = ACTIONS(95),
    [anon_sym_RPAREN] = ACTIONS(95),
    [anon_sym_LBRACK] = ACTIONS(95),
    [anon_sym_RBRACK] = ACTIONS(95),
    [anon_sym_LBRACE] = ACTIONS(95),
    [anon_sym_RBRACE] = ACTIONS(95),
    [anon_sym_COMMA] = ACTIONS(95),
    [anon_sym_DOT] = ACTIONS(97),
    [anon_sym_SEMI] = ACTIONS(95),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(99),
    [sym_identifier] = ACTIONS(101),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_kw_function] = ACTIONS(101),
    [anon_sym_class] = ACTIONS(101),
    [anon_sym_trait] = ACTIONS(101),
    [anon_sym_enum] = ACTIONS(101),
    [anon_sym_if] = ACTIONS(101),
    [anon_sym_else] = ACTIONS(101),
    [anon_sym_match] = ACTIONS(101),
    [anon_sym_cond] = ACTIONS(101),
    [anon_sym_while] = ACTIONS(101),
    [anon_sym_for] = ACTIONS(101),
    [anon_sym_in] = ACTIONS(101),
    [anon_sym_return] = ACTIONS(101),
    [anon_sym_break] = ACTIONS(101),
    [anon_sym_continue] = ACTIONS(101),
    [anon_sym_throw] = ACTIONS(101),
    [anon_sym_try] = ACTIONS(101),
    [anon_sym_catch] = ACTIONS(101),
    [anon_sym_defer] = ACTIONS(101),
    [anon_sym_yield] = ACTIONS(101),
    [anon_sym_import] = ACTIONS(101),
    [anon_sym_export] = ACTIONS(101),
    [anon_sym_from] = ACTIONS(101),
    [sym_kw_debugger] = ACTIONS(101),
    [anon_sym_let] = ACTIONS(101),
    [anon_sym_mut] = ACTIONS(101),
    [anon_sym_static] = ACTIONS(101),
    [anon_sym_true] = ACTIONS(101),
    [anon_sym_false] = ACTIONS(101),
    [sym_nil] = ACTIONS(101),
    [anon_sym_self] = ACTIONS(101),
    [anon_sym_this] = ACTIONS(101),
    [anon_sym___ARGS__] = ACTIONS(101),
    [sym_number] = ACTIONS(99),
    [sym_string] = ACTIONS(99),
    [sym_regex] = ACTIONS(99),
    [sym_type] = ACTIONS(99),
    [sym_operator] = ACTIONS(101),
    [anon_sym_LPAREN2] = ACTIONS(99),
    [anon_sym_RPAREN] = ACTIONS(99),
    [anon_sym_LBRACK] = ACTIONS(99),
    [anon_sym_RBRACK] = ACTIONS(99),
    [anon_sym_LBRACE] = ACTIONS(99),
    [anon_sym_RBRACE] = ACTIONS(99),
    [anon_sym_COMMA] = ACTIONS(99),
    [anon_sym_DOT] = ACTIONS(101),
    [anon_sym_SEMI] = ACTIONS(99),
  },
  [STATE(8)] = {
    [ts_builtin_sym_end] = ACTIONS(103),
    [sym_identifier] = ACTIONS(105),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_kw_function] = ACTIONS(105),
    [anon_sym_class] = ACTIONS(105),
    [anon_sym_trait] = ACTIONS(105),
    [anon_sym_enum] = ACTIONS(105),
    [anon_sym_if] = ACTIONS(105),
    [anon_sym_else] = ACTIONS(105),
    [anon_sym_match] = ACTIONS(105),
    [anon_sym_cond] = ACTIONS(105),
    [anon_sym_while] = ACTIONS(105),
    [anon_sym_for] = ACTIONS(105),
    [anon_sym_in] = ACTIONS(105),
    [anon_sym_return] = ACTIONS(105),
    [anon_sym_break] = ACTIONS(105),
    [anon_sym_continue] = ACTIONS(105),
    [anon_sym_throw] = ACTIONS(105),
    [anon_sym_try] = ACTIONS(105),
    [anon_sym_catch] = ACTIONS(105),
    [anon_sym_defer] = ACTIONS(105),
    [anon_sym_yield] = ACTIONS(105),
    [anon_sym_import] = ACTIONS(105),
    [anon_sym_export] = ACTIONS(105),
    [anon_sym_from] = ACTIONS(105),
    [sym_kw_debugger] = ACTIONS(105),
    [anon_sym_let] = ACTIONS(105),
    [anon_sym_mut] = ACTIONS(105),
    [anon_sym_static] = ACTIONS(105),
    [anon_sym_true] = ACTIONS(105),
    [anon_sym_false] = ACTIONS(105),
    [sym_nil] = ACTIONS(105),
    [anon_sym_self] = ACTIONS(105),
    [anon_sym_this] = ACTIONS(105),
    [anon_sym___ARGS__] = ACTIONS(105),
    [sym_number] = ACTIONS(103),
    [sym_string] = ACTIONS(103),
    [sym_regex] = ACTIONS(103),
    [sym_type] = ACTIONS(103),
    [sym_operator] = ACTIONS(105),
    [anon_sym_LPAREN2] = ACTIONS(103),
    [anon_sym_RPAREN] = ACTIONS(103),
    [anon_sym_LBRACK] = ACTIONS(103),
    [anon_sym_RBRACK] = ACTIONS(103),
    [anon_sym_LBRACE] = ACTIONS(103),
    [anon_sym_RBRACE] = ACTIONS(103),
    [anon_sym_COMMA] = ACTIONS(103),
    [anon_sym_DOT] = ACTIONS(105),
    [anon_sym_SEMI] = ACTIONS(103),
  },
  [STATE(9)] = {
    [ts_builtin_sym_end] = ACTIONS(107),
    [sym_identifier] = ACTIONS(109),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_kw_function] = ACTIONS(109),
    [anon_sym_class] = ACTIONS(109),
    [anon_sym_trait] = ACTIONS(109),
    [anon_sym_enum] = ACTIONS(109),
    [anon_sym_if] = ACTIONS(109),
    [anon_sym_else] = ACTIONS(109),
    [anon_sym_match] = ACTIONS(109),
    [anon_sym_cond] = ACTIONS(109),
    [anon_sym_while] = ACTIONS(109),
    [anon_sym_for] = ACTIONS(109),
    [anon_sym_in] = ACTIONS(109),
    [anon_sym_return] = ACTIONS(109),
    [anon_sym_break] = ACTIONS(109),
    [anon_sym_continue] = ACTIONS(109),
    [anon_sym_throw] = ACTIONS(109),
    [anon_sym_try] = ACTIONS(109),
    [anon_sym_catch] = ACTIONS(109),
    [anon_sym_defer] = ACTIONS(109),
    [anon_sym_yield] = ACTIONS(109),
    [anon_sym_import] = ACTIONS(109),
    [anon_sym_export] = ACTIONS(109),
    [anon_sym_from] = ACTIONS(109),
    [sym_kw_debugger] = ACTIONS(109),
    [anon_sym_let] = ACTIONS(109),
    [anon_sym_mut] = ACTIONS(109),
    [anon_sym_static] = ACTIONS(109),
    [anon_sym_true] = ACTIONS(109),
    [anon_sym_false] = ACTIONS(109),
    [sym_nil] = ACTIONS(109),
    [anon_sym_self] = ACTIONS(109),
    [anon_sym_this] = ACTIONS(109),
    [anon_sym___ARGS__] = ACTIONS(109),
    [sym_number] = ACTIONS(107),
    [sym_string] = ACTIONS(107),
    [sym_regex] = ACTIONS(107),
    [sym_type] = ACTIONS(107),
    [sym_operator] = ACTIONS(109),
    [anon_sym_LPAREN2] = ACTIONS(107),
    [anon_sym_RPAREN] = ACTIONS(107),
    [anon_sym_LBRACK] = ACTIONS(107),
    [anon_sym_RBRACK] = ACTIONS(107),
    [anon_sym_LBRACE] = ACTIONS(107),
    [anon_sym_RBRACE] = ACTIONS(107),
    [anon_sym_COMMA] = ACTIONS(107),
    [anon_sym_DOT] = ACTIONS(109),
    [anon_sym_SEMI] = ACTIONS(107),
  },
  [STATE(10)] = {
    [ts_builtin_sym_end] = ACTIONS(111),
    [sym_identifier] = ACTIONS(113),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_kw_function] = ACTIONS(113),
    [anon_sym_class] = ACTIONS(113),
    [anon_sym_trait] = ACTIONS(113),
    [anon_sym_enum] = ACTIONS(113),
    [anon_sym_if] = ACTIONS(113),
    [anon_sym_else] = ACTIONS(113),
    [anon_sym_match] = ACTIONS(113),
    [anon_sym_cond] = ACTIONS(113),
    [anon_sym_while] = ACTIONS(113),
    [anon_sym_for] = ACTIONS(113),
    [anon_sym_in] = ACTIONS(113),
    [anon_sym_return] = ACTIONS(113),
    [anon_sym_break] = ACTIONS(113),
    [anon_sym_continue] = ACTIONS(113),
    [anon_sym_throw] = ACTIONS(113),
    [anon_sym_try] = ACTIONS(113),
    [anon_sym_catch] = ACTIONS(113),
    [anon_sym_defer] = ACTIONS(113),
    [anon_sym_yield] = ACTIONS(113),
    [anon_sym_import] = ACTIONS(113),
    [anon_sym_export] = ACTIONS(113),
    [anon_sym_from] = ACTIONS(113),
    [sym_kw_debugger] = ACTIONS(113),
    [anon_sym_let] = ACTIONS(113),
    [anon_sym_mut] = ACTIONS(113),
    [anon_sym_static] = ACTIONS(113),
    [anon_sym_true] = ACTIONS(113),
    [anon_sym_false] = ACTIONS(113),
    [sym_nil] = ACTIONS(113),
    [anon_sym_self] = ACTIONS(113),
    [anon_sym_this] = ACTIONS(113),
    [anon_sym___ARGS__] = ACTIONS(113),
    [sym_number] = ACTIONS(111),
    [sym_string] = ACTIONS(111),
    [sym_regex] = ACTIONS(111),
    [sym_type] = ACTIONS(111),
    [sym_operator] = ACTIONS(113),
    [anon_sym_LPAREN2] = ACTIONS(111),
    [anon_sym_RPAREN] = ACTIONS(111),
    [anon_sym_LBRACK] = ACTIONS(111),
    [anon_sym_RBRACK] = ACTIONS(111),
    [anon_sym_LBRACE] = ACTIONS(111),
    [anon_sym_RBRACE] = ACTIONS(111),
    [anon_sym_COMMA] = ACTIONS(111),
    [anon_sym_DOT] = ACTIONS(113),
    [anon_sym_SEMI] = ACTIONS(111),
  },
  [STATE(11)] = {
    [ts_builtin_sym_end] = ACTIONS(115),
    [sym_identifier] = ACTIONS(117),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_kw_function] = ACTIONS(117),
    [anon_sym_class] = ACTIONS(117),
    [anon_sym_trait] = ACTIONS(117),
    [anon_sym_enum] = ACTIONS(117),
    [anon_sym_if] = ACTIONS(117),
    [anon_sym_else] = ACTIONS(117),
    [anon_sym_match] = ACTIONS(117),
    [anon_sym_cond] = ACTIONS(117),
    [anon_sym_while] = ACTIONS(117),
    [anon_sym_for] = ACTIONS(117),
    [anon_sym_in] = ACTIONS(117),
    [anon_sym_return] = ACTIONS(117),
    [anon_sym_break] = ACTIONS(117),
    [anon_sym_continue] = ACTIONS(117),
    [anon_sym_throw] = ACTIONS(117),
    [anon_sym_try] = ACTIONS(117),
    [anon_sym_catch] = ACTIONS(117),
    [anon_sym_defer] = ACTIONS(117),
    [anon_sym_yield] = ACTIONS(117),
    [anon_sym_import] = ACTIONS(117),
    [anon_sym_export] = ACTIONS(117),
    [anon_sym_from] = ACTIONS(117),
    [sym_kw_debugger] = ACTIONS(117),
    [anon_sym_let] = ACTIONS(117),
    [anon_sym_mut] = ACTIONS(117),
    [anon_sym_static] = ACTIONS(117),
    [anon_sym_true] = ACTIONS(117),
    [anon_sym_false] = ACTIONS(117),
    [sym_nil] = ACTIONS(117),
    [anon_sym_self] = ACTIONS(117),
    [anon_sym_this] = ACTIONS(117),
    [anon_sym___ARGS__] = ACTIONS(117),
    [sym_number] = ACTIONS(115),
    [sym_string] = ACTIONS(115),
    [sym_regex] = ACTIONS(115),
    [sym_type] = ACTIONS(115),
    [sym_operator] = ACTIONS(117),
    [anon_sym_LPAREN2] = ACTIONS(115),
    [anon_sym_RPAREN] = ACTIONS(115),
    [anon_sym_LBRACK] = ACTIONS(115),
    [anon_sym_RBRACK] = ACTIONS(115),
    [anon_sym_LBRACE] = ACTIONS(115),
    [anon_sym_RBRACE] = ACTIONS(115),
    [anon_sym_COMMA] = ACTIONS(115),
    [anon_sym_DOT] = ACTIONS(117),
    [anon_sym_SEMI] = ACTIONS(115),
  },
  [STATE(12)] = {
    [ts_builtin_sym_end] = ACTIONS(119),
    [sym_identifier] = ACTIONS(121),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_kw_function] = ACTIONS(121),
    [anon_sym_class] = ACTIONS(121),
    [anon_sym_trait] = ACTIONS(121),
    [anon_sym_enum] = ACTIONS(121),
    [anon_sym_if] = ACTIONS(121),
    [anon_sym_else] = ACTIONS(121),
    [anon_sym_match] = ACTIONS(121),
    [anon_sym_cond] = ACTIONS(121),
    [anon_sym_while] = ACTIONS(121),
    [anon_sym_for] = ACTIONS(121),
    [anon_sym_in] = ACTIONS(121),
    [anon_sym_return] = ACTIONS(121),
    [anon_sym_break] = ACTIONS(121),
    [anon_sym_continue] = ACTIONS(121),
    [anon_sym_throw] = ACTIONS(121),
    [anon_sym_try] = ACTIONS(121),
    [anon_sym_catch] = ACTIONS(121),
    [anon_sym_defer] = ACTIONS(121),
    [anon_sym_yield] = ACTIONS(121),
    [anon_sym_import] = ACTIONS(121),
    [anon_sym_export] = ACTIONS(121),
    [anon_sym_from] = ACTIONS(121),
    [sym_kw_debugger] = ACTIONS(121),
    [anon_sym_let] = ACTIONS(121),
    [anon_sym_mut] = ACTIONS(121),
    [anon_sym_static] = ACTIONS(121),
    [anon_sym_true] = ACTIONS(121),
    [anon_sym_false] = ACTIONS(121),
    [sym_nil] = ACTIONS(121),
    [anon_sym_self] = ACTIONS(121),
    [anon_sym_this] = ACTIONS(121),
    [anon_sym___ARGS__] = ACTIONS(121),
    [sym_number] = ACTIONS(119),
    [sym_string] = ACTIONS(119),
    [sym_regex] = ACTIONS(119),
    [sym_type] = ACTIONS(119),
    [sym_operator] = ACTIONS(121),
    [anon_sym_LPAREN2] = ACTIONS(119),
    [anon_sym_RPAREN] = ACTIONS(119),
    [anon_sym_LBRACK] = ACTIONS(119),
    [anon_sym_RBRACK] = ACTIONS(119),
    [anon_sym_LBRACE] = ACTIONS(119),
    [anon_sym_RBRACE] = ACTIONS(119),
    [anon_sym_COMMA] = ACTIONS(119),
    [anon_sym_DOT] = ACTIONS(121),
    [anon_sym_SEMI] = ACTIONS(119),
  },
  [STATE(13)] = {
    [ts_builtin_sym_end] = ACTIONS(123),
    [sym_identifier] = ACTIONS(125),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_kw_function] = ACTIONS(125),
    [anon_sym_class] = ACTIONS(125),
    [anon_sym_trait] = ACTIONS(125),
    [anon_sym_enum] = ACTIONS(125),
    [anon_sym_if] = ACTIONS(125),
    [anon_sym_else] = ACTIONS(125),
    [anon_sym_match] = ACTIONS(125),
    [anon_sym_cond] = ACTIONS(125),
    [anon_sym_while] = ACTIONS(125),
    [anon_sym_for] = ACTIONS(125),
    [anon_sym_in] = ACTIONS(125),
    [anon_sym_return] = ACTIONS(125),
    [anon_sym_break] = ACTIONS(125),
    [anon_sym_continue] = ACTIONS(125),
    [anon_sym_throw] = ACTIONS(125),
    [anon_sym_try] = ACTIONS(125),
    [anon_sym_catch] = ACTIONS(125),
    [anon_sym_defer] = ACTIONS(125),
    [anon_sym_yield] = ACTIONS(125),
    [anon_sym_import] = ACTIONS(125),
    [anon_sym_export] = ACTIONS(125),
    [anon_sym_from] = ACTIONS(125),
    [sym_kw_debugger] = ACTIONS(125),
    [anon_sym_let] = ACTIONS(125),
    [anon_sym_mut] = ACTIONS(125),
    [anon_sym_static] = ACTIONS(125),
    [anon_sym_true] = ACTIONS(125),
    [anon_sym_false] = ACTIONS(125),
    [sym_nil] = ACTIONS(125),
    [anon_sym_self] = ACTIONS(125),
    [anon_sym_this] = ACTIONS(125),
    [anon_sym___ARGS__] = ACTIONS(125),
    [sym_number] = ACTIONS(123),
    [sym_string] = ACTIONS(123),
    [sym_regex] = ACTIONS(123),
    [sym_type] = ACTIONS(123),
    [sym_operator] = ACTIONS(125),
    [anon_sym_LPAREN2] = ACTIONS(123),
    [anon_sym_RPAREN] = ACTIONS(123),
    [anon_sym_LBRACK] = ACTIONS(123),
    [anon_sym_RBRACK] = ACTIONS(123),
    [anon_sym_LBRACE] = ACTIONS(123),
    [anon_sym_RBRACE] = ACTIONS(123),
    [anon_sym_COMMA] = ACTIONS(123),
    [anon_sym_DOT] = ACTIONS(125),
    [anon_sym_SEMI] = ACTIONS(123),
  },
  [STATE(14)] = {
    [ts_builtin_sym_end] = ACTIONS(127),
    [sym_identifier] = ACTIONS(129),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_kw_function] = ACTIONS(129),
    [anon_sym_class] = ACTIONS(129),
    [anon_sym_trait] = ACTIONS(129),
    [anon_sym_enum] = ACTIONS(129),
    [anon_sym_if] = ACTIONS(129),
    [anon_sym_else] = ACTIONS(129),
    [anon_sym_match] = ACTIONS(129),
    [anon_sym_cond] = ACTIONS(129),
    [anon_sym_while] = ACTIONS(129),
    [anon_sym_for] = ACTIONS(129),
    [anon_sym_in] = ACTIONS(129),
    [anon_sym_return] = ACTIONS(129),
    [anon_sym_break] = ACTIONS(129),
    [anon_sym_continue] = ACTIONS(129),
    [anon_sym_throw] = ACTIONS(129),
    [anon_sym_try] = ACTIONS(129),
    [anon_sym_catch] = ACTIONS(129),
    [anon_sym_defer] = ACTIONS(129),
    [anon_sym_yield] = ACTIONS(129),
    [anon_sym_import] = ACTIONS(129),
    [anon_sym_export] = ACTIONS(129),
    [anon_sym_from] = ACTIONS(129),
    [sym_kw_debugger] = ACTIONS(129),
    [anon_sym_let] = ACTIONS(129),
    [anon_sym_mut] = ACTIONS(129),
    [anon_sym_static] = ACTIONS(129),
    [anon_sym_true] = ACTIONS(129),
    [anon_sym_false] = ACTIONS(129),
    [sym_nil] = ACTIONS(129),
    [anon_sym_self] = ACTIONS(129),
    [anon_sym_this] = ACTIONS(129),
    [anon_sym___ARGS__] = ACTIONS(129),
    [sym_number] = ACTIONS(127),
    [sym_string] = ACTIONS(127),
    [sym_regex] = ACTIONS(127),
    [sym_type] = ACTIONS(127),
    [sym_operator] = ACTIONS(129),
    [anon_sym_LPAREN2] = ACTIONS(127),
    [anon_sym_RPAREN] = ACTIONS(127),
    [anon_sym_LBRACK] = ACTIONS(127),
    [anon_sym_RBRACK] = ACTIONS(127),
    [anon_sym_LBRACE] = ACTIONS(127),
    [anon_sym_RBRACE] = ACTIONS(127),
    [anon_sym_COMMA] = ACTIONS(127),
    [anon_sym_DOT] = ACTIONS(129),
    [anon_sym_SEMI] = ACTIONS(127),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(131), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(15)] = 0,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [64] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [67] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [70] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [82] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__token, 1, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__token, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_kw_class, 1, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_kw_class, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_kw_conditional, 1, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_kw_conditional, 1, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_kw_repeat, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_kw_repeat, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_kw_statement, 1, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_kw_statement, 1, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_kw_include, 1, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_kw_include, 1, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_storage, 1, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_storage, 1, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self, 1, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self, 1, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_punctuation, 1, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_punctuation, 1, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 2, 0, 1),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 2, 0, 1),
  [131] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_culebra(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
