#!/bin/sh
# Set up Culebra for Vim / Neovim: syntax highlighting, and (for Neovim) a
# ready-to-source nvim-dap debug config.
#
# - Syntax highlighting: installs cul.vim + ftdetect (filetype `cul`) into
#   ~/.vim and ~/.config/nvim — whichever exist (delegates to
#   install-vim-syntax.sh).
# - Debugging (Neovim, nvim-dap): writes a self-contained Lua module that
#   registers the `culebra dap` adapter and a launch config keyed on the `cul`
#   filetype, then prints the one line to add to your init.lua. The culebra
#   path is baked in when it's on PATH. (No init.lua is edited automatically.)
#
# classic Vim uses vimspector, whose config is per-project (.vimspector.json) —
# this script prints that snippet rather than installing it globally.

set -eu

SRC_DIR=$(cd "$(dirname "$0")" && pwd)

# 1. Syntax highlighting (Vim + Neovim).
"$SRC_DIR/install-vim-syntax.sh"

# 2. Neovim nvim-dap config (only if a Neovim config dir exists).
NVIM="$HOME/.config/nvim"
CULEBRA=$(command -v culebra 2>/dev/null || echo culebra)
if [ -d "$NVIM" ]; then
  mkdir -p "$NVIM/lua"
  cat > "$NVIM/lua/culebra_dap.lua" <<LUA
-- Culebra nvim-dap setup. Enable by adding to your init.lua:
--     require("culebra_dap")
-- Generated by misc/vim/install.sh.
local ok, dap = pcall(require, "dap")
if not ok then
  vim.notify("culebra_dap: nvim-dap not found", vim.log.levels.WARN)
  return
end

dap.adapters.culebra = {
  type = "executable",
  command = "$CULEBRA",
  args = { "dap" },
}

dap.configurations.cul = {
  {
    type = "culebra",
    request = "launch",
    name = "Debug file",
    program = "\${file}",
    cwd = "\${workspaceFolder}",
    stopOnEntry = false,
  },
}
LUA
  echo "installed nvim-dap config: $NVIM/lua/culebra_dap.lua (adapter: $CULEBRA dap)"
  echo "  -> add this line to your init.lua to enable it:"
  echo "       require(\"culebra_dap\")"
  echo "  -> then: :lua require('dap').toggle_breakpoint() and :lua require('dap').continue()"
  echo "  -> a variables/stack UI: install nvim-dap-ui (rcarriga/nvim-dap-ui)"
else
  echo "no ~/.config/nvim — skipped nvim-dap config (Neovim not set up)"
fi

# 3. classic Vim (vimspector) is per-project — print the snippet to copy.
cat <<EOF

For classic Vim with vimspector, add .vimspector.json to your project root:

  {
    "configurations": {
      "Debug file": {
        "adapter": { "command": ["$CULEBRA", "dap"] },
        "configuration": { "request": "launch", "program": "\${file}", "stopOnEntry": false }
      }
    }
  }
EOF
