#pragma once

// Canonical native-signature tables: what every stdlib native (Ns.method,
// bare global) and every value-type built-in method (.map / .split / ...)
// declares — parameter names, types, defaults, keyword-only/rest markers,
// and positional arity bounds. This is the compiled lanes' single source for
// binding and diagnostics; it was derived from the tree-walker's own
// parameter tables while both engines existed (Phase 4 B7-a), and the data
// lives in canon_sigs.gen.h, regenerated by tools/gen_canon_sigs.cc
// (`just gen-canon-sigs`; `just check-canon-sigs` is the sync gate).
//
// Nothing here touches the interpreter, LLVM, or the GC — plain std types
// over constexpr arrays — so vm::Compiler, the JIT runtime, and the AOT
// archive can all read one copy of the binder's facts.

#include <cstddef>
#include <cstdint>
#include <span>
#include <string>
#include <string_view>
#include <unordered_map>

namespace culebra {

// A parameter default's payload discriminator. Canonical stdlib defaults are
// only ever these literal scalars; the generator emits the enumerator names,
// and _jit_default_from_canon (stdlib_jit.h) decodes them.
enum class CanonDefault : int8_t { None, Nil, Bool, Long, Float, Str };

// One declared parameter. Field names/types intentionally match the uses the
// JIT binder grew against the interp's FunctionValue::Parameter (`.name`,
// `.has_default`, `.kw_only`, `.type` as string_views), so the resolver and
// trampoline read it unchanged.
struct CanonParam {
  std::string_view name;
  bool has_default = false;
  bool kw_only = false;
  bool kwargs_rest = false;
  bool args_rest = false;
  bool mut = false;
  // Declared type annotation ("String" / "Function" / ...); empty = untyped.
  std::string_view type;
  // Default payload: `default_bits` carries Bool/Long values and a Float's
  // bit pattern; `default_str` a Str's text.
  CanonDefault default_kind = CanonDefault::None;
  int64_t default_bits = 0;
  std::string_view default_str;
};

// One method's full signature. `min_arity`/`max_arity`/`variadic` are the
// `builtin_arity_bounds` result precomputed at generation time; the three
// indices are first-occurrence positions (-1 = none), matching what the
// kwarg resolver derives today.
struct CanonSig {
  std::string_view ns;    // "" = bare global / value-type table entry
  std::string_view sub;   // "" = no nested sub-namespace
  std::string_view name;
  const CanonParam* params;
  int n_params;
  std::string_view return_type;  // "" = none declared
  int min_arity;
  int max_arity;
  bool variadic;
  int kwargs_rest_idx;    // -1 = none
  int first_kw_only_idx;  // -1 = none
  int args_rest_idx;      // -1 = none
};

}  // namespace culebra

#include "canon_sigs.gen.h"

namespace culebra {

using CanonSigTable = std::unordered_map<std::string_view, const CanonSig*>;

namespace _canon_detail {
inline CanonSigTable build(std::span<const CanonSig> sigs) {
  CanonSigTable m;
  m.reserve(sigs.size());
  for (const auto& s : sigs) m.emplace(s.name, &s);
  return m;
}
}  // namespace _canon_detail

// The one spelling of the (ns, sub, name) map key — every builder and every
// lookup goes through this, so the encoding cannot drift between them.
inline std::string canon_sig_key(std::string_view ns, std::string_view sub,
                                 std::string_view name) {
  std::string key;
  key.reserve(ns.size() + sub.size() + name.size() + 2);
  key.append(ns).push_back('\0');
  key.append(sub).push_back('\0');
  key.append(name);
  return key;
}

// The value-type built-in method tables, keyed by method name — the exact
// receiver split interp's eval_property dispatched on (String and StringView
// share one table by construction; the generator emits it once). The
// stdlib-native rows (kCanonNsSigs) have no accessor here: their one reader
// is stdlib_jit.h's _canon_sig, which merges them with the wrap-declared
// rows into a single registry.
inline const CanonSigTable& canon_object_sigs() {
  static const CanonSigTable t = _canon_detail::build(kCanonObjectSigs);
  return t;
}
inline const CanonSigTable& canon_array_sigs() {
  static const CanonSigTable t = _canon_detail::build(kCanonArraySigs);
  return t;
}
inline const CanonSigTable& canon_string_sigs() {
  static const CanonSigTable t = _canon_detail::build(kCanonStringSigs);
  return t;
}
inline const CanonSigTable& canon_set_sigs() {
  static const CanonSigTable t = _canon_detail::build(kCanonSetSigs);
  return t;
}
inline const CanonSigTable& canon_tuple_sigs() {
  static const CanonSigTable t = _canon_detail::build(kCanonTupleSigs);
  return t;
}
inline const CanonSigTable& canon_tensor_sigs() {
  static const CanonSigTable t = _canon_detail::build(kCanonTensorSigs);
  return t;
}
inline const CanonSigTable& canon_iterator_sigs() {
  static const CanonSigTable t = _canon_detail::build(kCanonIteratorSigs);
  return t;
}

}  // namespace culebra
