// Generates include/grammar_blob.gen.h from culebra::grammar_ (grammar_def.h).
//
// Run via `just gen-blob` after changing the grammar or bumping
// vendor/cpp-peglib — the blob layout is peglib-version-specific. Skipping it
// is safe but silent: get_parser() guards the blob with GRAMMAR_BLOB_HASH and
// falls back to load_grammar(), which costs ~10 ms on every startup. `--check`
// (via `just check-blob`) fails when the checked-in header is stale.
#include "grammar_blob_key.h"  // culebra::grammar_blob_key() (+ grammar_, CPPPEGLIB_VERSION)
#include "peglib.h"

#include <cstdarg>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

namespace {

void appendf(std::string& out, const char* fmt, ...) {
  char buf[256];
  va_list args;
  va_start(args, fmt);
  std::vsnprintf(buf, sizeof(buf), fmt, args);
  va_end(args);
  out += buf;
}

std::string read_file(const char* path) {
  FILE* f = std::fopen(path, "rb");
  if (!f) return {};
  std::string out;
  char buf[8192];
  size_t n;
  while ((n = std::fread(buf, 1, sizeof(buf), f)) > 0) out.append(buf, n);
  std::fclose(f);
  return out;
}

}  // namespace

int main(int argc, char** argv) {
  bool check = false;
  const char* out = "include/grammar_blob.gen.h";
  for (int i = 1; i < argc; ++i) {
    if (std::strcmp(argv[i], "--check") == 0) {
      check = true;
    } else {
      out = argv[i];
    }
  }

  peg::parser parser;
  parser.set_logger([](size_t, size_t, const std::string&) {});
  if (!parser.load_grammar(culebra::grammar_)) {
    std::fprintf(stderr, "gen_grammar_blob: load_grammar failed\n");
    return 1;
  }
  parser.enable_ast();
  parser.enable_packrat_parsing();

  std::vector<uint8_t> blob;
  try {
    blob = parser.serialize_grammar();
  } catch (const std::exception& e) {
    std::fprintf(stderr, "gen_grammar_blob: serialize failed: %s\n", e.what());
    return 1;
  }

  const uint64_t hash = culebra::grammar_blob_key();

  std::string text;
  text += "#pragma once\n";
  text += "// GENERATED by tools/gen_grammar_blob.cc (`just gen-blob`). Do not edit.\n";
  text += "// Serialized cpp-peglib grammar for culebra::grammar_ — lets get_parser()\n";
  text += "// skip the meta-parse. GRAMMAR_BLOB_HASH keys the blob to the grammar text\n";
  appendf(text, "// AND the cpp-peglib version (%s here); get_parser() falls back to\n", CPPPEGLIB_VERSION);
  text += "// load_grammar() whenever either changes (stale blob).\n";
  text += "#include <cstddef>\n#include <cstdint>\n\nnamespace culebra {\n\n";
  appendf(text, "inline constexpr uint64_t GRAMMAR_BLOB_HASH = 0x%016llxULL;\n\n",
          static_cast<unsigned long long>(hash));
  text += "inline constexpr unsigned char GRAMMAR_BLOB[] = {\n";
  for (size_t i = 0; i < blob.size(); ++i) {
    appendf(text, "0x%02x,", blob[i]);
    if ((i % 20) == 19) text += "\n";
  }
  text += "\n};\n\ninline constexpr size_t GRAMMAR_BLOB_SIZE = sizeof(GRAMMAR_BLOB);\n\n";
  text += "}  // namespace culebra\n";

  if (check) {
    if (read_file(out) == text) return 0;
    std::fprintf(stderr,
                 "gen_grammar_blob: %s is stale (grammar or cpp-peglib changed).\n"
                 "  Run `just gen-blob` and commit the result — a stale blob silently\n"
                 "  costs ~10 ms of startup by falling back to load_grammar().\n",
                 out);
    return 1;
  }

  FILE* f = std::fopen(out, "w");
  if (!f) {
    std::fprintf(stderr, "gen_grammar_blob: cannot open %s\n", out);
    return 1;
  }
  std::fwrite(text.data(), 1, text.size(), f);
  std::fclose(f);

  std::fprintf(stderr, "gen_grammar_blob: wrote %s (%zu bytes, hash %016llx)\n", out,
               blob.size(), static_cast<unsigned long long>(hash));
  return 0;
}
