// Generates include/grammar_blob.h from culebra::grammar_ (grammar_def.h).
//
// Run via `just gen-blob` after changing the grammar or bumping
// vendor/cpp-peglib — the blob layout is peglib-version-specific. Skipping it
// is safe: get_parser() guards the blob with GRAMMAR_BLOB_HASH and falls back
// to load_grammar() when it doesn't match the current grammar.
#include "grammar_blob_key.h"  // culebra::grammar_blob_key() (+ grammar_, CPPPEGLIB_VERSION)
#include "peglib.h"

#include <cstdint>
#include <cstdio>
#include <vector>

int main(int argc, char** argv) {
  const char* out = argc > 1 ? argv[1] : "include/grammar_blob.h";

  peg::parser parser;
  parser.set_logger([](size_t, size_t, const std::string&) {});
  if (!parser.load_grammar(culebra::grammar_)) {
    std::fprintf(stderr, "gen_grammar_blob: load_grammar failed\n");
    return 1;
  }
  parser.enable_ast();
  parser.enable_packrat_parsing();

  std::vector<uint8_t> blob;
  try {
    blob = parser.serialize_grammar();
  } catch (const std::exception& e) {
    std::fprintf(stderr, "gen_grammar_blob: serialize failed: %s\n", e.what());
    return 1;
  }

  const uint64_t hash = culebra::grammar_blob_key();

  FILE* f = std::fopen(out, "w");
  if (!f) {
    std::fprintf(stderr, "gen_grammar_blob: cannot open %s\n", out);
    return 1;
  }
  std::fprintf(f, "#pragma once\n");
  std::fprintf(f, "// GENERATED by tools/gen_grammar_blob.cc (`just gen-blob`). Do not edit.\n");
  std::fprintf(f, "// Serialized cpp-peglib grammar for culebra::grammar_ — lets get_parser()\n");
  std::fprintf(f, "// skip the meta-parse. GRAMMAR_BLOB_HASH keys the blob to the grammar text\n");
  std::fprintf(f, "// AND the cpp-peglib version (%s here); get_parser() falls back to\n", CPPPEGLIB_VERSION);
  std::fprintf(f, "// load_grammar() whenever either changes (stale blob).\n");
  std::fprintf(f, "#include <cstddef>\n#include <cstdint>\n\nnamespace culebra {\n\n");
  std::fprintf(f, "inline constexpr uint64_t GRAMMAR_BLOB_HASH = 0x%016llxULL;\n\n",
               static_cast<unsigned long long>(hash));
  std::fprintf(f, "inline constexpr unsigned char GRAMMAR_BLOB[] = {\n");
  for (size_t i = 0; i < blob.size(); ++i) {
    std::fprintf(f, "0x%02x,", blob[i]);
    if ((i % 20) == 19) std::fprintf(f, "\n");
  }
  std::fprintf(f, "\n};\n\ninline constexpr size_t GRAMMAR_BLOB_SIZE = sizeof(GRAMMAR_BLOB);\n\n");
  std::fprintf(f, "}  // namespace culebra\n");
  std::fclose(f);

  std::fprintf(stderr, "gen_grammar_blob: wrote %s (%zu bytes, hash %016llx)\n", out,
               blob.size(), static_cast<unsigned long long>(hash));
  return 0;
}
