# Generate build_info.cc: what `culebra --version` appends to CULEBRA_VERSION
# so a development build is never mistaken for the release that shares its
# version number.
#
# The version itself stays include/culebra.h's — only the suffix comes from
# here. Reading the version off `git describe` instead would give two sources
# of truth, and they disagree exactly when it matters: between a version bump
# and the tag that follows it.
#
# The tag's own spelling is never parsed. `--long` always answers
# <tag>-<n>-g<hash>, so the count and the hash come off the end and a tag named
# v0.4.0 or 0.4.0 reads the same. n == 0 with a clean tree is the release case
# and gets an empty suffix, which is what keeps a release binary printing a
# bare version. `--always` covers a checkout with no tag in reach (a shallow CI
# clone): it answers with the bare commit, which no <tag>-<n>-g form can be
# read out of, and carries its own -dirty.
#
# Usage: cmake -DSRC_DIR=<checkout> -DOUT=<file> -P gen_build_info.cmake

set(suffix "")

find_program(GIT_EXE git)
# A worktree's .git is a file, not a directory; EXISTS covers both. Neither is
# there in a source archive, which is the case that keeps the suffix empty.
if(GIT_EXE AND EXISTS "${SRC_DIR}/.git")
  execute_process(
    COMMAND ${GIT_EXE} -C "${SRC_DIR}" describe --tags --long --dirty --always
    OUTPUT_VARIABLE described OUTPUT_STRIP_TRAILING_WHITESPACE
    RESULT_VARIABLE described_rc ERROR_QUIET)

  if(described_rc EQUAL 0)
    if(described MATCHES "-([0-9]+)-(g[0-9a-f]+)(-dirty)?$")
      if(NOT CMAKE_MATCH_1 EQUAL 0)
        set(suffix "-${CMAKE_MATCH_1}-${CMAKE_MATCH_2}")
      endif()
      string(APPEND suffix "${CMAKE_MATCH_3}")
    else()
      set(suffix "-g${described}")
    endif()
  endif()
endif()

set(content
"// Generated by cmake/gen_build_info.cmake at build time. Not committed.
#include \"build_info.h\"

namespace culebra {

const char* build_suffix() { return \"${suffix}\"; }

}  // namespace culebra
")

# Rewrite only on a change: this runs on every build, and touching the file
# would cost a recompile and a relink every time.
set(previous "")
if(EXISTS "${OUT}")
  file(READ "${OUT}" previous)
endif()
if(NOT previous STREQUAL content)
  file(WRITE "${OUT}" "${content}")
endif()
